import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "company", title: "Company", default: true },
    { name: "contact", title: "Contact" },
    { name: "nav", title: "Header & Footer" },
    { name: "labels", title: "UI labels" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "name", title: "Company name", type: "string", group: "company", initialValue: "Excellanto", validation: (Rule) => Rule.required() }),
    defineField({ name: "tagline", title: "Tagline", type: "string", group: "company", initialValue: "AI Powered IT Solutions & Staffing" }),
    defineField({ name: "description", title: "Company description", type: "text", rows: 5, group: "company" }),
    defineField({ name: "url", title: "Website URL", type: "url", group: "company" }),
    defineField({ name: "logo", title: "Logo", type: "siteImage", group: "company" }),
    defineField({ name: "phone", title: "Primary phone", type: "string", group: "contact" }),
    defineField({ name: "phoneSecondary", title: "Secondary phone", type: "string", group: "contact" }),
    defineField({ name: "email", title: "Primary email", type: "string", group: "contact" }),
    defineField({ name: "emailSecondary", title: "Secondary email", type: "string", group: "contact" }),
    defineField({ name: "address", title: "Address", type: "text", rows: 3, group: "contact" }),
    defineField({ name: "facebook", title: "Facebook URL", type: "url", group: "contact" }),
    defineField({ name: "instagram", title: "Instagram URL", type: "url", group: "contact" }),
    defineField({ name: "linkedin", title: "LinkedIn URL", type: "url", group: "contact" }),
    defineField({
      name: "navLinks",
      title: "Header navigation",
      type: "array",
      group: "nav",
      of: [{ type: "navLink" }],
    }),
    defineField({ name: "headerCta", title: "Header button", type: "ctaButton", group: "nav" }),
    defineField({ name: "primaryCta", title: "Default primary button", type: "ctaButton", group: "nav" }),
    defineField({ name: "secondaryCta", title: "Default secondary button", type: "ctaButton", group: "nav" }),
    defineField({
      name: "footerServicesTitle",
      title: "Footer column: Services title",
      type: "string",
      group: "nav",
      initialValue: "Services",
    }),
    defineField({
      name: "footerCompanyTitle",
      title: "Footer column: Quick links title",
      type: "string",
      group: "nav",
      initialValue: "Quick Links",
    }),
    defineField({
      name: "footerResourcesTitle",
      title: "Footer column: Resources title",
      type: "string",
      group: "nav",
      initialValue: "say hello",
    }),
    defineField({
      name: "footerCompanyLinks",
      title: "Footer quick links",
      type: "array",
      group: "nav",
      of: [{ type: "navLink" }],
    }),
    defineField({
      name: "footerResourceLinks",
      title: "Footer resource links",
      type: "array",
      group: "nav",
      of: [{ type: "navLink" }],
    }),
    defineField({
      name: "copyright",
      title: "Copyright text",
      type: "string",
      group: "nav",
      description: "Year is added automatically. Example: All Rights Reserved by Excellanto Ventures",
    }),
    defineField({
      name: "footerTagline",
      title: "Footer tagline",
      type: "string",
      group: "nav",
    }),
    defineField({ name: "skipToContent", title: "Skip to content", type: "string", group: "labels", initialValue: "Skip to content" }),
    defineField({ name: "viewMore", title: "View more", type: "string", group: "labels", initialValue: "View More" }),
    defineField({ name: "viewAllServices", title: "View all services", type: "string", group: "labels", initialValue: "View all services" }),
    defineField({ name: "backToServices", title: "Back to services", type: "string", group: "labels", initialValue: "Services" }),
    defineField({ name: "backToBlog", title: "Back to blog", type: "string", group: "labels", initialValue: "Back to Blog" }),
    defineField({ name: "openMenu", title: "Open menu (accessibility)", type: "string", group: "labels", initialValue: "Open menu" }),
    defineField({ name: "closeMenu", title: "Close menu (accessibility)", type: "string", group: "labels", initialValue: "Close menu" }),
    defineField({ name: "logoAriaLabel", title: "Logo accessibility label", type: "string", group: "labels", initialValue: "Excellanto home" }),
    defineField({ name: "megaMenuAria", title: "Services menu accessibility label", type: "string", group: "labels", initialValue: "Services mega menu" }),
    defineField({ name: "serviceEyebrow", title: "Service page eyebrow", type: "string", group: "labels", initialValue: "Service" }),
    defineField({ name: "byPrefix", title: "Author prefix", type: "string", group: "labels", initialValue: "By" }),
    defineField({ name: "articleFallbackTitle", title: "Missing article title", type: "string", group: "labels", initialValue: "Article" }),
    defineField({ name: "primaryNavAria", title: "Primary nav accessibility label", type: "string", group: "labels", initialValue: "Primary" }),
    defineField({ name: "mobileNavAria", title: "Mobile nav accessibility label", type: "string", group: "labels", initialValue: "Mobile" }),
    defineField({ name: "seoTitle", title: "Default SEO title", type: "string", group: "seo" }),
    defineField({ name: "seoDescription", title: "Default SEO description", type: "text", rows: 3, group: "seo" }),
    defineField({ name: "seoAuthor", title: "SEO author", type: "string", group: "seo", initialValue: "Excellanto Ventures" }),
    defineField({
      name: "seoKeywords",
      title: "SEO keywords",
      type: "array",
      group: "seo",
      of: [{ type: "string" }],
    }),
  ],
  preview: {
    prepare() {
      return { title: "Site Settings" };
    },
  },
});
